[project]
name = "fredrik-advent-of-code"
version = "2025"
requires-python = ">=3.13"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["aoc"]

[tool.uv.workspace]
members = [
    "2025/10",
]
